/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"

class TimeLagFilterAudioProcessor;
class MainComponent;


//==============================================================================
/**
*/
class TimeLagFilterAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    TimeLagFilterAudioProcessorEditor (TimeLagFilterAudioProcessor&);
    ~TimeLagFilterAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

    ScopedPointer<MainComponent> mainComponent;
    
private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    TimeLagFilterAudioProcessor& processor;
    

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (TimeLagFilterAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
