/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "MainComponent.h"


//==============================================================================
TimeLagFilterAudioProcessorEditor::TimeLagFilterAudioProcessorEditor (TimeLagFilterAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p){
    
    addAndMakeVisible(mainComponent = new MainComponent(processor));
    mainComponent->setBounds(0, 0, 960, 600);
    
    setSize (960, 600);
}

TimeLagFilterAudioProcessorEditor::~TimeLagFilterAudioProcessorEditor(){
    
}

//==============================================================================
void TimeLagFilterAudioProcessorEditor::paint (Graphics& g){
    
}

void TimeLagFilterAudioProcessorEditor::resized(){
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..
}
